### ISSUE TITLE
Transfer pod initialization error reported against ImageConversion Step.

### ISSUE THREAD

**Issue by jortel** [kubev2v/forklift-controller#66]
Transfer pod initialization error reported against ImageConversion Step instead of DiskTransfer step.
The error is reported by VMIO since it starts the pod.

**Comment by jortel** [comment]
This will be fixed when VMIO functionality moved to MTV controller.  Recommend we don't fix until then.

**Comment by ahadas** [comment]
With the upcoming changes in how virt-v2v is used, there would be a single step for transferring and converting the disks so this issue would not be relevant anymore
